name: Deploy to GitHub Pages
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
concurrency:
    group: "pages"
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Checkout linglong old version
              run: |
                # 定义版本和 commit 的映射关系
                declare -A dict=(
                    ["1.5.0"]="317ef66813e413adafeae5b01186b34eda514248"
                    # 添加更多的版本和 commit
                )
                # 遍历字典并检出每个 commit 到对应的目录
                for version in "${!dict[@]}"; do
                    commit="${dict[$version]}"
                    # 克隆仓库到指定版本的目录下，使用一个临时分支名
                    git clone https://github.com/OpenAtomFoundation/linglong.git $version
                    cd $version
                    git sparse-checkout init
                    git sparse-checkout set docs/pages/en docs/pages/guide
                    git checkout $commit
                    mv docs/pages/en .
                    mv docs/pages/guide .
                    # 输出目录内容，确认文件是否被正确检出
                    cd ..
                done
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Checkout linglong release
              uses: actions/checkout@v4
              with:
                  ref: 90f0846d2e9b0ed14e6f51e40c3a25b5de35dd93 # 指定玲珑项目的 commit 提交，可能文档有小部分修改，不需要从 tag 获取
                  path: tmp
                  repository: OpenAtomFoundation/linglong
                  sparse-checkout: |
                      docs/pages
                  sparse-checkout-cone-mode: false
            - name: set release version
              run: |
                  rm -rf en guide
                  mv tmp/docs/pages/guide .
                  mv tmp/docs/pages/en .
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "yarn"
            - name: Install Depend
              run: yarn install
            - name: Build Pages
              run: yarn build
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./.vitepress/dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
